xplane_directory: "<<path-to-your-xplane-main-directory>>"
expected_failures: 2
mtbf_hours: 3
scenario_name: "MyScenario.sce"
state_probability_overrides:
  ias: 0
  tas: 0
  # Disabling all speed triggers (but v1) reduces chances of chaotic takeoff (airspeed increase has many trigger chances)
  vr: 0
  v2: 0
  vt: 0
  gs: 0
overrides:
  systems:
    eng:
      left:
        mult: 5
        combust:
          instability:
            state: 4
            param: 7
      right:
        ign:
          A:
            state: 1
          B:
            mtbf_hours: 2